### ISSUE TITLE
MapInit error

### ISSUE THREAD

**Issue by tforkmann** [fable-elmish/browser#55] opened 2022-12-08 12:46 UTC
Hi there,

updating to the newest Elmish (4.0.0-beta-8) produces following error:

> String.js:522 Uncaught (in promise) Error: Invalid startIndex and/or length
    at substring (String.js:522:15)
    at parseParams (parser.fs.js:274:72)
    at parsePath (parser.fs.js:5:56)
    at urlParser (Pages.js:197:21)
    at init (navigation.fs.js:96:56)
    at Program$4.init (Util.js:552:12)
    at traceInit (program.fs.js:66:38)
    at init (debugger.fs.js:36:30)
    at Util.js:552:12
    at mapInit (App.js:2909:42)
> 

I didn't make any changes from the version 3 to version 4 yet. 

<img width="420" alt="image" src="https://user-images.githubusercontent.com/4168951/206449686-a264d84f-d782-4b7b-96bc-b6972f7d6d36.png">

Any idea how to fix that?

**Comment by et1975** [comment] 2022-12-08 13:39
Hm, there was [this fix](https://github.com/elmish/browser/issues/50)...

**Comment by tforkmann** [comment] 2022-12-08 14:42
Hmm that fix was for hashes right?

**Comment by tforkmann** [comment] 2022-12-08 14:43
I guess it would need the same fix of parsePath instead of parseHash. Gonna try to create a PR.

**Comment by et1975** [comment] 2022-12-26 15:56
@alfonsogarciacaro  I've created a [unit test that](https://github.com/et1975/urlParser/commit/7ea99b5df1d9ea636af441f1ec9805016870d5dc) passes (w/ or w/o the check in line 357) when running in CLR, which tells me the `substring` impl in JS doesn't work the same way as `String.Substring`  - JS throws exception if start position points at the end, while .NET - returns empty string. Do you think this should be addressed in Fable core?

**Comment by et1975** [comment] 2022-12-28 13:31
will release a fix in urlParser 1.0.1.

**Closed as completed by et1975** 2022-12-28 13:31 UTC

**Comment by alfonsogarciacaro** [comment] 2022-12-29 06:05
@et1975 The [substring implementation](https://github.com/fable-compiler/Fable/blob/10b0e161e44051243a52101b6c8c2209d7b4a64f/src/fable-library/String.ts#L561-L566) seems to be right in Fable (it will return an empty string if startIndex is same as length). Maybe the error is caused by something else?
